FROM postgres:17.4 AS ps-img

# DB setup parameters
ENV POSTGRES_USER=superset_user
ENV POSTGRES_PASSWORD=superset_pass
ENV POSTGRES_DB=superset_db

# create functions
#COPY flesch_reading_score.sql /docker-entrypoint-initdb.d/
# create table
#COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
